[theme]
base = "dark"
primaryColor = "#0A66C2"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0f172a"
textColor = "#e2e8f0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false